apiVersion: v1
items:
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      kubernetes.io/limit-ranger: 'LimitRanger plugin set: cpu, memory request for
        container nexus3; cpu, memory limit for container nexus3'
      openshift.io/deployment-config.latest-version: "1"
      openshift.io/deployment-config.name: nexus3
      openshift.io/deployment.name: nexus3-1
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/scc: restricted
    creationTimestamp: 2018-10-15T19:28:22Z
    generateName: nexus3-1-
    labels:
      app: nexus3
      deployment: nexus3-1
      deploymentconfig: nexus3
    name: nexus3-1-bw7w5
    namespace: 1ff3-nexus
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicationController
      name: nexus3-1
      uid: 7063e615-d0b0-11e8-af65-0220bffb280e
    resourceVersion: "74431903"
    selfLink: /api/v1/namespaces/1ff3-nexus/pods/nexus3-1-bw7w5
    uid: 7aaa4925-d0b0-11e8-af65-0220bffb280e
  spec:
    containers:
    - image: docker.io/sonatype/nexus3@sha256:262f9f2b5e61ebbee068a23acfdad8283d8b9285b9f99a8b38bb8c65b2a13071
      imagePullPolicy: Always
      name: nexus3
      ports:
      - containerPort: 8081
        protocol: TCP
      resources:
        limits:
          cpu: 500m
          memory: 1536Mi
        requests:
          cpu: 50m
          memory: 256Mi
      securityContext:
        capabilities:
          drop:
          - KILL
          - MKNOD
          - SETGID
          - SETUID
        runAsUser: 1019470000
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /nexus-data
        name: nexus3-volume-1
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-zw8lw
        readOnly: true
    dnsPolicy: ClusterFirst
    imagePullSecrets:
    - name: default-dockercfg-whcpl
    nodeName: node8.na39.internal
    nodeSelector:
      env: users
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 1019470000
      seLinuxOptions:
        level: s0:c140,c5
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    tolerations:
    - effect: NoSchedule
      key: node.kubernetes.io/memory-pressure
      operator: Exists
    volumes:
    - emptyDir: {}
      name: nexus3-volume-1
    - name: default-token-zw8lw
      secret:
        defaultMode: 420
        secretName: default-token-zw8lw
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: 2018-10-15T19:28:22Z
      status: "True"
      type: Initialized
    - lastProbeTime: null
      lastTransitionTime: 2018-10-15T19:28:37Z
      status: "True"
      type: Ready
    - lastProbeTime: null
      lastTransitionTime: 2018-10-15T19:28:22Z
      status: "True"
      type: PodScheduled
    containerStatuses:
    - containerID: docker://88fe1de70137085207bcbfb1e9b41627c5f1c04d02282e692d3da961bd3b1e69
      image: docker.io/sonatype/nexus3@sha256:262f9f2b5e61ebbee068a23acfdad8283d8b9285b9f99a8b38bb8c65b2a13071
      imageID: docker-pullable://docker.io/sonatype/nexus3@sha256:262f9f2b5e61ebbee068a23acfdad8283d8b9285b9f99a8b38bb8c65b2a13071
      lastState: {}
      name: nexus3
      ready: true
      restartCount: 0
      state:
        running:
          startedAt: 2018-10-15T19:28:36Z
    hostIP: 192.199.0.91
    phase: Running
    podIP: 10.1.12.79
    qosClass: Burstable
    startTime: 2018-10-15T19:28:22Z
- apiVersion: v1
  kind: ReplicationController
  metadata:
    annotations:
      openshift.io/deployer-pod.completed-at: 2018-10-15 19:28:38 +0000 UTC
      openshift.io/deployer-pod.created-at: 2018-10-15 19:28:05 +0000 UTC
      openshift.io/deployer-pod.name: nexus3-1-deploy
      openshift.io/deployment-config.latest-version: "1"
      openshift.io/deployment-config.name: nexus3
      openshift.io/deployment.phase: Complete
      openshift.io/deployment.replicas: "1"
      openshift.io/deployment.status-reason: config change
      openshift.io/encoded-deployment-config: |
        {"kind":"DeploymentConfig","apiVersion":"v1","metadata":{"name":"nexus3","namespace":"1ff3-nexus","selfLink":"/apis/apps.openshift.io/v1/namespaces/1ff3-nexus/deploymentconfigs/nexus3","uid":"6fe49772-d0b0-11e8-af65-0220bffb280e","resourceVersion":"74431561","generation":2,"creationTimestamp":"2018-10-15T19:28:04Z","labels":{"app":"nexus3"},"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ConfigChange"},{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["nexus3"],"from":{"kind":"ImageStreamTag","namespace":"1ff3-nexus","name":"nexus3:latest"},"lastTriggeredImage":"docker.io/sonatype/nexus3@sha256:262f9f2b5e61ebbee068a23acfdad8283d8b9285b9f99a8b38bb8c65b2a13071"}}],"replicas":1,"revisionHistoryLimit":10,"test":false,"selector":{"app":"nexus3","deploymentconfig":"nexus3"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"nexus3","deploymentconfig":"nexus3"},"annotations":{"openshift.io/generated-by":"OpenShiftNewApp"}},"spec":{"volumes":[{"name":"nexus3-volume-1","emptyDir":{}}],"containers":[{"name":"nexus3","image":"docker.io/sonatype/nexus3@sha256:262f9f2b5e61ebbee068a23acfdad8283d8b9285b9f99a8b38bb8c65b2a13071","ports":[{"containerPort":8081,"protocol":"TCP"}],"resources":{},"volumeMounts":[{"name":"nexus3-volume-1","mountPath":"/nexus-data"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":1,"observedGeneration":1,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"config change","causes":[{"type":"ConfigChange"}]},"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2018-10-15T19:28:04Z","lastTransitionTime":"2018-10-15T19:28:04Z","message":"Deployment config does not have minimum availability."}]}}
    creationTimestamp: 2018-10-15T19:28:05Z
    generation: 2
    labels:
      app: nexus3
      openshift.io/deployment-config.name: nexus3
    name: nexus3-1
    namespace: 1ff3-nexus
    ownerReferences:
    - apiVersion: apps.openshift.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: DeploymentConfig
      name: nexus3
      uid: 6fe49772-d0b0-11e8-af65-0220bffb280e
    resourceVersion: "74431928"
    selfLink: /api/v1/namespaces/1ff3-nexus/replicationcontrollers/nexus3-1
    uid: 7063e615-d0b0-11e8-af65-0220bffb280e
  spec:
    replicas: 1
    selector:
      app: nexus3
      deployment: nexus3-1
      deploymentconfig: nexus3
    template:
      metadata:
        annotations:
          openshift.io/deployment-config.latest-version: "1"
          openshift.io/deployment-config.name: nexus3
          openshift.io/deployment.name: nexus3-1
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: nexus3
          deployment: nexus3-1
          deploymentconfig: nexus3
      spec:
        containers:
        - image: docker.io/sonatype/nexus3@sha256:262f9f2b5e61ebbee068a23acfdad8283d8b9285b9f99a8b38bb8c65b2a13071
          imagePullPolicy: Always
          name: nexus3
          ports:
          - containerPort: 8081
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /nexus-data
            name: nexus3-volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: nexus3-volume-1
  status:
    availableReplicas: 1
    fullyLabeledReplicas: 1
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: 2018-10-15T19:47:16Z
    labels:
      app: nexus3
    name: nexus-registry
    namespace: 1ff3-nexus
    resourceVersion: "74441604"
    selfLink: /api/v1/namespaces/1ff3-nexus/services/nexus-registry
    uid: 1e555f86-d0b3-11e8-af65-0220bffb280e
  spec:
    clusterIP: 172.30.46.201
    ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
    selector:
      app: nexus3
      deploymentconfig: nexus3
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: 2018-10-15T19:28:04Z
    labels:
      app: nexus3
    name: nexus3
    namespace: 1ff3-nexus
    resourceVersion: "74431551"
    selfLink: /api/v1/namespaces/1ff3-nexus/services/nexus3
    uid: 7000388c-d0b0-11e8-af65-0220bffb280e
  spec:
    clusterIP: 172.30.222.198
    ports:
    - name: 8081-tcp
      port: 8081
      protocol: TCP
      targetPort: 8081
    selector:
      app: nexus3
      deploymentconfig: nexus3
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: 2018-10-15T19:28:04Z
    generation: 8
    labels:
      app: nexus3
    name: nexus3
    namespace: 1ff3-nexus
    resourceVersion: "74432797"
    selfLink: /apis/apps.openshift.io/v1/namespaces/1ff3-nexus/deploymentconfigs/nexus3
    uid: 6fe49772-d0b0-11e8-af65-0220bffb280e
  spec:
    paused: true
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      app: nexus3
      deploymentconfig: nexus3
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Recreate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: nexus3
          deploymentconfig: nexus3
      spec:
        containers:
        - image: docker.io/sonatype/nexus3@sha256:262f9f2b5e61ebbee068a23acfdad8283d8b9285b9f99a8b38bb8c65b2a13071
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
              - echo
              - ok
            failureThreshold: 3
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          name: nexus3
          ports:
          - containerPort: 8081
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /repository/maven-public/
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
            requests:
              cpu: 500m
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /nexus-data
            name: nexus3-volume-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: nexus3-volume-1
          persistentVolumeClaim:
            claimName: nexus-pvc
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - nexus3
        from:
          kind: ImageStreamTag
          name: nexus3:latest
          namespace: 1ff3-nexus
        lastTriggeredImage: docker.io/sonatype/nexus3@sha256:262f9f2b5e61ebbee068a23acfdad8283d8b9285b9f99a8b38bb8c65b2a13071
      type: ImageChange
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2018-10-15T19:28:38Z
      lastUpdateTime: 2018-10-15T19:28:38Z
      message: Deployment config has minimum availability.
      status: "True"
      type: Available
    - lastTransitionTime: 2018-10-15T19:28:40Z
      lastUpdateTime: 2018-10-15T19:28:40Z
      message: replication controller "nexus3-1" successfully rolled out
      reason: NewReplicationControllerAvailable
      status: "True"
      type: Progressing
    details:
      causes:
      - type: ConfigChange
      message: config change
    latestVersion: 1
    observedGeneration: 8
    readyReplicas: 1
    replicas: 1
    unavailableReplicas: 0
    updatedReplicas: 1
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/image.dockerRepositoryCheck: 2018-10-15T19:28:05Z
    creationTimestamp: 2018-10-15T19:28:04Z
    generation: 2
    labels:
      app: nexus3
    name: nexus3
    namespace: 1ff3-nexus
    resourceVersion: "74431559"
    selfLink: /apis/image.openshift.io/v1/namespaces/1ff3-nexus/imagestreams/nexus3
    uid: 6fca105d-d0b0-11e8-af65-0220bffb280e
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: docker.io/sonatype/nexus3:latest
      from:
        kind: DockerImage
        name: docker.io/sonatype/nexus3:latest
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: docker-registry.default.svc:5000/1ff3-nexus/nexus3
    tags:
    - items:
      - created: 2018-10-15T19:28:05Z
        dockerImageReference: docker.io/sonatype/nexus3@sha256:262f9f2b5e61ebbee068a23acfdad8283d8b9285b9f99a8b38bb8c65b2a13071
        generation: 2
        image: sha256:262f9f2b5e61ebbee068a23acfdad8283d8b9285b9f99a8b38bb8c65b2a13071
      tag: latest
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: 2018-10-15T19:47:17Z
    labels:
      app: nexus3
    name: nexus-registry
    namespace: 1ff3-nexus
    resourceVersion: "74441612"
    selfLink: /apis/route.openshift.io/v1/namespaces/1ff3-nexus/routes/nexus-registry
    uid: 1ef01a72-d0b3-11e8-af65-0220bffb280e
  spec:
    host: nexus-registry-1ff3-nexus.apps.na39.openshift.opentlc.com
    port:
      targetPort: 5000
    tls:
      termination: edge
    to:
      kind: Service
      name: nexus-registry
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2018-10-15T19:47:17Z
        status: "True"
        type: Admitted
      host: nexus-registry-1ff3-nexus.apps.na39.openshift.opentlc.com
      routerName: router
      wildcardPolicy: None
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    creationTimestamp: 2018-10-15T19:28:48Z
    labels:
      app: nexus3
    name: nexus3
    namespace: 1ff3-nexus
    resourceVersion: "74432002"
    selfLink: /apis/route.openshift.io/v1/namespaces/1ff3-nexus/routes/nexus3
    uid: 8a3acd8e-d0b0-11e8-af65-0220bffb280e
  spec:
    host: nexus3-1ff3-nexus.apps.na39.openshift.opentlc.com
    port:
      targetPort: 8081-tcp
    to:
      kind: Service
      name: nexus3
      weight: 100
    wildcardPolicy: None
  status:
    ingress:
    - conditions:
      - lastTransitionTime: 2018-10-15T19:28:48Z
        status: "True"
        type: Admitted
      host: nexus3-1ff3-nexus.apps.na39.openshift.opentlc.com
      routerName: router
      wildcardPolicy: None
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
